// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University.Domain.Presistent;

#nullable disable

namespace University.Infrasructure.Migrations;

[DbContext(typeof(UniversityDbContext))]
[Migration("20230311122005_AddMyEntities")]
partial class AddMyEntities
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("University.Domain.Entities.Course", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("CREATE_AT");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("DESCRIPTION");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("UPDATE_AT");

                b.HasKey("Id");

                b.ToTable("Courses");
            });

        modelBuilder.Entity("University.Domain.Entities.Group", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CourseID")
                    .HasColumnType("int")
                    .HasColumnName("COURSE_ID");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("CREATE_AT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("NAME");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("UPDATE_AT");

                b.HasKey("Id");

                b.ToTable("Groups");
            });

        modelBuilder.Entity("University.Domain.Entities.Student", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("CREATE_AT");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("FIRST_NAME");

                b.Property<int?>("GroupID")
                    .HasColumnType("int")
                    .HasColumnName("GROUP_ID");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("LAST_NAME");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2")
                    .HasColumnName("UPDATE_AT");

                b.HasKey("Id");

                b.ToTable("Students");
            });
#pragma warning restore 612, 618
    }
}
